version: 2
sources:
  - name: jaffle_shop
    description: The default schema for the first set of tables
    database: raw
    schema: jaffle_shop
    tables:
      - name: customers
        description: One record per customer.
      - name: orders
        description: One record per order. Includes cancelled and deleted orders.

  - name: stripes
    description: Schema containing payment data.
    database: raw
    schema: stripe
    tables:
      - name: payment
        description: One record per payment transaction.


